spring.application.name=EMPLOYEECRUD

spring.datasource.url=jdbc:mysql://localhost:3306/Employee_crud_db
spring.datasource.username=root
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true